// Auto-generated from the medical dataset CSVs. Do not edit by hand.

export interface DiseaseProfile {
  disease: string;
  symptoms: string[];
  description: string;
  precautions: string[];
}

export const DISEASE_PROFILES: DiseaseProfile[] = [
  {
    disease: "Fungal infection",
    symptoms: ["itching", "skin_rash", "nodal_skin_eruptions", "dischromic _patches"],
    description: "In humans, fungal infections occur when an invading fungus takes over an area of the body and is too much for the immune system to handle. Fungi can live in the air, soil, water, and plants. There are also some fungi that live naturally in the human body. Like many microbes, there are helpful fungi and harmful fungi.",
    precautions: ["bath twice", "use detol or neem in bathing water", "keep infected area dry", "use clean cloths"],
  },
  {
    disease: "Allergy",
    symptoms: ["continuous_sneezing", "shivering", "chills", "watering_from_eyes"],
    description: "An allergy is an immune system response to a foreign substance that's not typically harmful to your body.They can include certain foods, pollen, or pet dander. Your immune system's job is to keep you healthy by fighting harmful pathogens.",
    precautions: ["apply calamine", "cover area with bandage", "use ice to compress itching"],
  },
  {
    disease: "GERD",
    symptoms: ["stomach_pain", "acidity", "ulcers_on_tongue", "vomiting", "cough", "chest_pain"],
    description: "Gastroesophageal reflux disease, or GERD, is a digestive disorder that affects the lower esophageal sphincter (LES), the ring of muscle between the esophagus and stomach. Many people, including pregnant women, suffer from heartburn or acid indigestion caused by GERD.",
    precautions: ["avoid fatty spicy food", "avoid lying down after eating", "maintain healthy weight", "exercise"],
  },
  {
    disease: "Chronic cholestasis",
    symptoms: ["itching", "vomiting", "yellowish_skin", "nausea", "loss_of_appetite", "abdominal_pain", "yellowing_of_eyes"],
    description: "Chronic cholestatic diseases, whether occurring in infancy, childhood or adulthood, are characterized by defective bile acid transport from the liver to the intestine, which is caused by primary damage to the biliary epithelium in most cases",
    precautions: ["cold baths", "anti itch medicine", "consult doctor", "eat healthy"],
  },
  {
    disease: "Drug Reaction",
    symptoms: ["itching", "skin_rash", "stomach_pain", "burning_micturition", "spotting_ urination"],
    description: "An adverse drug reaction (ADR) is an injury caused by taking medication. ADRs may occur following a single dose or prolonged administration of a drug or result from the combination of two or more drugs.",
    precautions: ["stop irritation", "consult nearest hospital", "stop taking drug", "follow up"],
  },
  {
    disease: "Peptic ulcer diseae",
    symptoms: ["vomiting", "indigestion", "loss_of_appetite", "abdominal_pain", "passage_of_gases", "internal_itching"],
    description: "Peptic ulcer disease (PUD) is a break in the inner lining of the stomach, the first part of the small intestine, or sometimes the lower esophagus. An ulcer in the stomach is called a gastric ulcer, while one in the first part of the intestines is a duodenal ulcer.",
    precautions: ["avoid fatty spicy food", "consume probiotic food", "eliminate milk", "limit alcohol"],
  },
  {
    disease: "AIDS",
    symptoms: ["muscle_wasting", "patches_in_throat", "high_fever", "extra_marital_contacts"],
    description: "Acquired immunodeficiency syndrome (AIDS) is a chronic, potentially life-threatening condition caused by the human immunodeficiency virus (HIV). By damaging your immune system, HIV interferes with your body's ability to fight infection and disease.",
    precautions: ["avoid open cuts", "wear ppe if possible", "consult doctor", "follow up"],
  },
  {
    disease: "Diabetes",
    symptoms: ["fatigue", "weight_loss", "restlessness", "lethargy", "irregular_sugar_level", "blurred_and_distorted_vision", "obesity", "excessive_hunger", "increased_appetite", "polyuria"],
    description: "Diabetes is a disease that occurs when your blood glucose, also called blood sugar, is too high. Blood glucose is your main source of energy and comes from the food you eat. Insulin, a hormone made by the pancreas, helps glucose from food get into your cells to be used for energy.",
    precautions: ["have balanced diet", "exercise", "consult doctor", "follow up"],
  },
  {
    disease: "Gastroenteritis",
    symptoms: ["vomiting", "sunken_eyes", "dehydration", "diarrhoea"],
    description: "Gastroenteritis is an inflammation of the digestive tract, particularly the stomach, and large and small intestines. Viral and bacterial gastroenteritis are intestinal infections associated with symptoms of diarrhea , abdominal cramps, nausea , and vomiting .",
    precautions: ["stop eating solid food for while", "try taking small sips of water", "rest", "ease back into eating"],
  },
  {
    disease: "Bronchial Asthma",
    symptoms: ["fatigue", "cough", "high_fever", "breathlessness", "family_history", "mucoid_sputum"],
    description: "Bronchial asthma is a medical condition which causes the airway path of the lungs to swell and narrow. Due to this swelling, the air path produces excess mucus making it hard to breathe, which results in coughing, short breath, and wheezing. The disease is chronic and interferes with daily working.",
    precautions: ["switch to loose cloothing", "take deep breaths", "get away from trigger", "seek help"],
  },
  {
    disease: "Hypertension",
    symptoms: ["headache", "chest_pain", "dizziness", "loss_of_balance", "lack_of_concentration"],
    description: "Hypertension (HTN or HT), also known as high blood pressure (HBP), is a long-term medical condition in which the blood pressure in the arteries is persistently elevated. High blood pressure typically does not cause symptoms.",
    precautions: ["meditation", "salt baths", "reduce stress", "get proper sleep"],
  },
  {
    disease: "Migraine",
    symptoms: ["acidity", "indigestion", "headache", "blurred_and_distorted_vision", "excessive_hunger", "stiff_neck", "depression", "irritability", "visual_disturbances"],
    description: "A migraine can cause severe throbbing pain or a pulsing sensation, usually on one side of the head. It's often accompanied by nausea, vomiting, and extreme sensitivity to light and sound. Migraine attacks can last for hours to days, and the pain can be so severe that it interferes with your daily activities.",
    precautions: ["meditation", "reduce stress", "use poloroid glasses in sun", "consult doctor"],
  },
  {
    disease: "Cervical spondylosis",
    symptoms: ["back_pain", "weakness_in_limbs", "neck_pain", "dizziness", "loss_of_balance"],
    description: "Cervical spondylosis is a general term for age-related wear and tear affecting the spinal disks in your neck. As the disks dehydrate and shrink, signs of osteoarthritis develop, including bony projections along the edges of bones (bone spurs).",
    precautions: ["use heating pad or cold pack", "exercise", "take otc pain reliver", "consult doctor"],
  },
  {
    disease: "Paralysis (brain hemorrhage)",
    symptoms: ["vomiting", "headache", "weakness_of_one_body_side", "altered_sensorium"],
    description: "Intracerebral hemorrhage (ICH) is when blood suddenly bursts into brain tissue, causing damage to your brain. Symptoms usually appear suddenly during ICH. They include headache, weakness, confusion, and paralysis, particularly on one side of your body.",
    precautions: ["massage", "eat healthy", "exercise", "consult doctor"],
  },
  {
    disease: "Jaundice",
    symptoms: ["itching", "vomiting", "fatigue", "weight_loss", "high_fever", "yellowish_skin", "dark_urine", "abdominal_pain"],
    description: "Yellow staining of the skin and sclerae (the whites of the eyes) by abnormally high blood levels of the bile pigment bilirubin. The yellowing extends to other tissues and body fluids. Jaundice was once called the \"morbus regius\" (the regal disease) in the belief that only the touch of a king could cure it",
    precautions: ["drink plenty of water", "consume milk thistle", "eat fruits and high fiberous food", "medication"],
  },
  {
    disease: "Malaria",
    symptoms: ["chills", "vomiting", "high_fever", "sweating", "headache", "nausea", "diarrhoea", "muscle_pain"],
    description: "An infectious disease caused by protozoan parasites from the Plasmodium family that can be transmitted by the bite of the Anopheles mosquito or by a contaminated needle or transfusion. Falciparum malaria is the most deadly type.",
    precautions: ["Consult nearest hospital", "avoid oily food", "avoid non veg food", "keep mosquitos out"],
  },
  {
    disease: "Chicken pox",
    symptoms: ["itching", "skin_rash", "fatigue", "lethargy", "high_fever", "headache", "loss_of_appetite", "mild_fever", "swelled_lymph_nodes", "malaise", "red_spots_over_body"],
    description: "Chickenpox is a highly contagious disease caused by the varicella-zoster virus (VZV). It can cause an itchy, blister-like rash. The rash first appears on the chest, back, and face, and then spreads over the entire body, causing between 250 and 500 itchy blisters.",
    precautions: ["use neem in bathing", "consume neem leaves", "take vaccine", "avoid public places"],
  },
  {
    disease: "Dengue",
    symptoms: ["skin_rash", "chills", "joint_pain", "vomiting", "fatigue", "high_fever", "headache", "nausea", "loss_of_appetite", "pain_behind_the_eyes", "back_pain", "malaise", "muscle_pain", "red_spots_over_body"],
    description: "an acute infectious disease caused by a flavivirus (species Dengue virus of the genus Flavivirus), transmitted by aedes mosquitoes, and characterized by headache, severe joint pain, and a rash. \u2014 called also breakbone fever, dengue fever.",
    precautions: ["drink papaya leaf juice", "avoid fatty spicy food", "keep mosquitos away", "keep hydrated"],
  },
  {
    disease: "Typhoid",
    symptoms: ["chills", "vomiting", "fatigue", "high_fever", "headache", "nausea", "constipation", "abdominal_pain", "diarrhoea", "toxic_look_(typhos)", "belly_pain"],
    description: "An acute illness characterized by fever caused by infection with the bacterium Salmonella typhi. Typhoid fever has an insidious onset, with fever, headache, constipation, malaise, chills, and muscle pain. Diarrhea is uncommon, and vomiting is not usually severe.",
    precautions: ["eat high calorie vegitables", "antiboitic therapy", "consult doctor", "medication"],
  },
  {
    disease: "hepatitis A",
    symptoms: ["joint_pain", "vomiting", "yellowish_skin", "dark_urine", "nausea", "loss_of_appetite", "abdominal_pain", "diarrhoea", "mild_fever", "yellowing_of_eyes", "muscle_pain"],
    description: "Hepatitis A is a highly contagious liver infection caused by the hepatitis A virus. The virus is one of several types of hepatitis viruses that cause inflammation and affect your liver's ability to function.",
    precautions: ["Consult nearest hospital", "wash hands through", "avoid fatty spicy food", "medication"],
  },
  {
    disease: "Hepatitis B",
    symptoms: ["itching", "fatigue", "lethargy", "yellowish_skin", "dark_urine", "loss_of_appetite", "abdominal_pain", "yellow_urine", "yellowing_of_eyes", "malaise", "receiving_blood_transfusion", "receiving_unsterile_injections"],
    description: "Hepatitis B is an infection of your liver. It can cause scarring of the organ, liver failure, and cancer. It can be fatal if it isn't treated. It's spread when people come in contact with the blood, open sores, or body fluids of someone who has the hepatitis B virus.",
    precautions: ["consult nearest hospital", "vaccination", "eat healthy", "medication"],
  },
  {
    disease: "Hepatitis C",
    symptoms: ["fatigue", "yellowish_skin", "nausea", "loss_of_appetite", "yellowing_of_eyes", "family_history"],
    description: "Inflammation of the liver due to the hepatitis C virus (HCV), which is usually spread via blood transfusion (rare), hemodialysis, and needle sticks. The damage hepatitis C does to the liver can lead to cirrhosis and its complications as well as cancer.",
    precautions: ["Consult nearest hospital", "vaccination", "eat healthy", "medication"],
  },
  {
    disease: "Hepatitis D",
    symptoms: ["joint_pain", "vomiting", "fatigue", "yellowish_skin", "dark_urine", "nausea", "loss_of_appetite", "abdominal_pain", "yellowing_of_eyes"],
    description: "Hepatitis D, also known as the hepatitis delta virus, is an infection that causes the liver to become inflamed. This swelling can impair liver function and cause long-term liver problems, including liver scarring and cancer. The condition is caused by the hepatitis D virus (HDV).",
    precautions: ["consult doctor", "medication", "eat healthy", "follow up"],
  },
  {
    disease: "Hepatitis E",
    symptoms: ["joint_pain", "vomiting", "fatigue", "high_fever", "yellowish_skin", "dark_urine", "nausea", "loss_of_appetite", "abdominal_pain", "yellowing_of_eyes", "acute_liver_failure", "coma", "stomach_bleeding"],
    description: "A rare form of liver inflammation caused by infection with the hepatitis E virus (HEV). It is transmitted via food or drink handled by an infected person or through infected water supplies in areas where fecal matter may get into the water. Hepatitis E does not cause chronic liver disease.",
    precautions: ["stop alcohol consumption", "rest", "consult doctor", "medication"],
  },
  {
    disease: "Alcoholic hepatitis",
    symptoms: ["vomiting", "yellowish_skin", "abdominal_pain", "swelling_of_stomach", "distention_of_abdomen", "history_of_alcohol_consumption", "fluid_overload"],
    description: "Alcoholic hepatitis is a diseased, inflammatory condition of the liver caused by heavy alcohol consumption over an extended period of time. It's also aggravated by binge drinking and ongoing alcohol use. If you develop this condition, you must stop drinking alcohol",
    precautions: ["stop alcohol consumption", "consult doctor", "medication", "follow up"],
  },
  {
    disease: "Tuberculosis",
    symptoms: ["chills", "vomiting", "fatigue", "weight_loss", "cough", "high_fever", "breathlessness", "sweating", "loss_of_appetite", "mild_fever", "yellowing_of_eyes", "swelled_lymph_nodes", "malaise", "phlegm", "chest_pain", "blood_in_sputum"],
    description: "Tuberculosis (TB) is an infectious disease usually caused by Mycobacterium tuberculosis (MTB) bacteria. Tuberculosis generally affects the lungs, but can also affect other parts of the body. Most infections show no symptoms, in which case it is known as latent tuberculosis.",
    precautions: ["cover mouth", "consult doctor", "medication", "rest"],
  },
  {
    disease: "Common Cold",
    symptoms: ["continuous_sneezing", "chills", "fatigue", "cough", "high_fever", "headache", "swelled_lymph_nodes", "malaise", "phlegm", "throat_irritation", "redness_of_eyes", "sinus_pressure", "runny_nose", "congestion", "chest_pain", "loss_of_smell", "muscle_pain"],
    description: "The common cold is a viral infection of your nose and throat (upper respiratory tract). It's usually harmless, although it might not feel that way. Many types of viruses can cause a common cold.",
    precautions: ["drink vitamin c rich drinks", "take vapour", "avoid cold food", "keep fever in check"],
  },
  {
    disease: "Pneumonia",
    symptoms: ["chills", "fatigue", "cough", "high_fever", "breathlessness", "sweating", "malaise", "phlegm", "chest_pain", "fast_heart_rate", "rusty_sputum"],
    description: "Pneumonia is an infection in one or both lungs. Bacteria, viruses, and fungi cause it. The infection causes inflammation in the air sacs in your lungs, which are called alveoli. The alveoli fill with fluid or pus, making it difficult to breathe.",
    precautions: ["consult doctor", "medication", "rest", "follow up"],
  },
  {
    disease: "Dimorphic hemmorhoids(piles)",
    symptoms: ["constipation", "pain_during_bowel_movements", "pain_in_anal_region", "bloody_stool", "irritation_in_anus"],
    description: "",
    precautions: ["avoid fatty spicy food", "consume witch hazel", "warm bath with epsom salt", "consume alovera juice"],
  },
  {
    disease: "Heart attack",
    symptoms: ["vomiting", "breathlessness", "sweating", "chest_pain"],
    description: "The death of heart muscle due to the loss of blood supply. The loss of blood supply is usually caused by a complete blockage of a coronary artery, one of the arteries that supplies blood to the heart muscle.",
    precautions: ["call ambulance", "chew or swallow asprin", "keep calm"],
  },
  {
    disease: "Varicose veins",
    symptoms: ["fatigue", "cramps", "bruising", "obesity", "swollen_legs", "swollen_blood_vessels", "prominent_veins_on_calf"],
    description: "A vein that has enlarged and twisted, often appearing as a bulging, blue blood vessel that is clearly visible through the skin. Varicose veins are most common in older adults, particularly women, and occur especially on the legs.",
    precautions: ["lie down flat and raise the leg high", "use oinments", "use vein compression", "dont stand still for long"],
  },
  {
    disease: "Hypothyroidism",
    symptoms: ["fatigue", "weight_gain", "cold_hands_and_feets", "mood_swings", "lethargy", "dizziness", "puffy_face_and_eyes", "enlarged_thyroid", "brittle_nails", "swollen_extremeties", "depression", "irritability", "abnormal_menstruation"],
    description: "Hypothyroidism, also called underactive thyroid or low thyroid, is a disorder of the endocrine system in which the thyroid gland does not produce enough thyroid hormone.",
    precautions: ["reduce stress", "exercise", "eat healthy", "get proper sleep"],
  },
  {
    disease: "Hyperthyroidism",
    symptoms: ["fatigue", "mood_swings", "weight_loss", "restlessness", "sweating", "diarrhoea", "fast_heart_rate", "excessive_hunger", "muscle_weakness", "irritability", "abnormal_menstruation"],
    description: "Hyperthyroidism (overactive thyroid) occurs when your thyroid gland produces too much of the hormone thyroxine. Hyperthyroidism can accelerate your body's metabolism, causing unintentional weight loss and a rapid or irregular heartbeat.",
    precautions: ["eat healthy", "massage", "use lemon balm", "take radioactive iodine treatment"],
  },
  {
    disease: "Hypoglycemia",
    symptoms: ["vomiting", "fatigue", "anxiety", "sweating", "headache", "nausea", "blurred_and_distorted_vision", "excessive_hunger", "drying_and_tingling_lips", "slurred_speech", "irritability", "palpitations"],
    description: "Hypoglycemia is a condition in which your blood sugar (glucose) level is lower than normal. Glucose is your body's main energy source. Hypoglycemia is often related to diabetes treatment. But other drugs and a variety of conditions \u2014 many rare \u2014 can cause low blood sugar in people who don't have diabetes.",
    precautions: ["lie down on side", "check in pulse", "drink sugary drinks", "consult doctor"],
  },
  {
    disease: "Osteoarthristis",
    symptoms: ["joint_pain", "neck_pain", "knee_pain", "hip_joint_pain", "swelling_joints", "painful_walking"],
    description: "Osteoarthritis is the most common form of arthritis, affecting millions of people worldwide. It occurs when the protective cartilage that cushions the ends of your bones wears down over time.",
    precautions: ["acetaminophen", "consult nearest hospital", "follow up", "salt baths"],
  },
  {
    disease: "Arthritis",
    symptoms: ["muscle_weakness", "stiff_neck", "swelling_joints", "movement_stiffness", "painful_walking"],
    description: "Arthritis is the swelling and tenderness of one or more of your joints. The main symptoms of arthritis are joint pain and stiffness, which typically worsen with age. The most common types of arthritis are osteoarthritis and rheumatoid arthritis.",
    precautions: ["exercise", "use hot and cold therapy", "try acupuncture", "massage"],
  },
  {
    disease: "(vertigo) Paroymsal  Positional Vertigo",
    symptoms: ["vomiting", "headache", "nausea", "spinning_movements", "loss_of_balance", "unsteadiness"],
    description: "Benign paroxysmal positional vertigo (BPPV) is one of the most common causes of vertigo \u2014 the sudden sensation that you're spinning or that the inside of your head is spinning. Benign paroxysmal positional vertigo causes brief episodes of mild to intense dizziness.",
    precautions: ["lie down", "avoid sudden change in body", "avoid abrupt head movment", "relax"],
  },
  {
    disease: "Acne",
    symptoms: ["skin_rash", "pus_filled_pimples", "blackheads", "scurring"],
    description: "Acne vulgaris is the formation of comedones, papules, pustules, nodules, and/or cysts as a result of obstruction and inflammation of pilosebaceous units (hair follicles and their accompanying sebaceous gland). Acne develops on the face and upper trunk. It most often affects adolescents.",
    precautions: ["bath twice", "avoid fatty spicy food", "drink plenty of water", "avoid too many products"],
  },
  {
    disease: "Urinary tract infection",
    symptoms: ["burning_micturition", "bladder_discomfort", "foul_smell_of urine", "continuous_feel_of_urine"],
    description: "Urinary tract infection: An infection of the kidney, ureter, bladder, or urethra. Abbreviated UTI. Not everyone with a UTI has symptoms, but common symptoms include a frequent urge to urinate and pain or burning when urinating.",
    precautions: ["drink plenty of water", "increase vitamin c intake", "drink cranberry juice", "take probiotics"],
  },
  {
    disease: "Psoriasis",
    symptoms: ["skin_rash", "joint_pain", "skin_peeling", "silver_like_dusting", "small_dents_in_nails", "inflammatory_nails"],
    description: "Psoriasis is a common skin disorder that forms thick, red, bumpy patches covered with silvery scales. They can pop up anywhere, but most appear on the scalp, elbows, knees, and lower back. Psoriasis can't be passed from person to person. It does sometimes happen in members of the same family.",
    precautions: ["wash hands with warm soapy water", "stop bleeding using pressure", "consult doctor", "salt baths"],
  },
  {
    disease: "Impetigo",
    symptoms: ["skin_rash", "high_fever", "blister", "red_sore_around_nose", "yellow_crust_ooze"],
    description: "Impetigo (im-puh-TIE-go) is a common and highly contagious skin infection that mainly affects infants and children. Impetigo usually appears as red sores on the face, especially around a child's nose and mouth, and on hands and feet. The sores burst and develop honey-colored crusts.",
    precautions: ["soak affected area in warm water", "use antibiotics", "remove scabs with wet compressed cloth", "consult doctor"],
  },
];

export const SYMPTOM_SEVERITY: Record<string, number> = {
  "abdominal_pain": 4,
  "abnormal_menstruation": 6,
  "acidity": 3,
  "acute_liver_failure": 6,
  "altered_sensorium": 2,
  "anxiety": 4,
  "back_pain": 3,
  "belly_pain": 4,
  "blackheads": 2,
  "bladder_discomfort": 4,
  "blister": 4,
  "blood_in_sputum": 5,
  "bloody_stool": 5,
  "blurred_and_distorted_vision": 5,
  "breathlessness": 4,
  "brittle_nails": 5,
  "bruising": 4,
  "burning_micturition": 6,
  "chest_pain": 7,
  "chills": 3,
  "cold_hands_and_feets": 5,
  "coma": 7,
  "congestion": 5,
  "constipation": 4,
  "continuous_feel_of_urine": 6,
  "continuous_sneezing": 4,
  "cough": 4,
  "cramps": 4,
  "dark_urine": 4,
  "dehydration": 4,
  "depression": 3,
  "diarrhoea": 6,
  "dischromic_patches": 6,
  "distention_of_abdomen": 4,
  "dizziness": 4,
  "drying_and_tingling_lips": 4,
  "enlarged_thyroid": 6,
  "excessive_hunger": 4,
  "extra_marital_contacts": 5,
  "family_history": 5,
  "fast_heart_rate": 5,
  "fatigue": 4,
  "fluid_overload": 4,
  "foul_smell_ofurine": 5,
  "headache": 3,
  "high_fever": 7,
  "hip_joint_pain": 2,
  "history_of_alcohol_consumption": 5,
  "increased_appetite": 5,
  "indigestion": 5,
  "inflammatory_nails": 2,
  "internal_itching": 4,
  "irregular_sugar_level": 5,
  "irritability": 2,
  "irritation_in_anus": 6,
  "itching": 1,
  "joint_pain": 3,
  "knee_pain": 3,
  "lack_of_concentration": 3,
  "lethargy": 2,
  "loss_of_appetite": 4,
  "loss_of_balance": 4,
  "loss_of_smell": 3,
  "malaise": 6,
  "mild_fever": 5,
  "mood_swings": 3,
  "movement_stiffness": 5,
  "mucoid_sputum": 4,
  "muscle_pain": 2,
  "muscle_wasting": 3,
  "muscle_weakness": 2,
  "nausea": 5,
  "neck_pain": 5,
  "nodal_skin_eruptions": 4,
  "obesity": 4,
  "pain_behind_the_eyes": 4,
  "pain_during_bowel_movements": 5,
  "pain_in_anal_region": 6,
  "painful_walking": 2,
  "palpitations": 4,
  "passage_of_gases": 5,
  "patches_in_throat": 6,
  "phlegm": 5,
  "polyuria": 4,
  "prognosis": 5,
  "prominent_veins_on_calf": 6,
  "puffy_face_and_eyes": 5,
  "pus_filled_pimples": 2,
  "receiving_blood_transfusion": 5,
  "receiving_unsterile_injections": 2,
  "red_sore_around_nose": 2,
  "red_spots_over_body": 3,
  "redness_of_eyes": 5,
  "restlessness": 5,
  "runny_nose": 5,
  "rusty_sputum": 4,
  "scurring": 2,
  "shivering": 5,
  "silver_like_dusting": 2,
  "sinus_pressure": 4,
  "skin_peeling": 3,
  "skin_rash": 3,
  "slurred_speech": 4,
  "small_dents_in_nails": 2,
  "spinning_movements": 6,
  "spotting_urination": 6,
  "stiff_neck": 4,
  "stomach_bleeding": 6,
  "stomach_pain": 5,
  "sunken_eyes": 3,
  "sweating": 3,
  "swelled_lymph_nodes": 6,
  "swelling_joints": 5,
  "swelling_of_stomach": 7,
  "swollen_blood_vessels": 5,
  "swollen_extremeties": 5,
  "swollen_legs": 5,
  "throat_irritation": 4,
  "toxic_look_(typhos)": 5,
  "ulcers_on_tongue": 4,
  "unsteadiness": 4,
  "visual_disturbances": 3,
  "vomiting": 5,
  "watering_from_eyes": 4,
  "weakness_in_limbs": 7,
  "weakness_of_one_body_side": 4,
  "weight_gain": 3,
  "weight_loss": 3,
  "yellow_crust_ooze": 3,
  "yellow_urine": 4,
  "yellowing_of_eyes": 4,
  "yellowish_skin": 3,
};

